vim.opt.background = "dark"
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "anticuus"

local set = vim.api.nvim_set_hl

-- Base
set(0, "Normal", { fg = "#dadada", bg = "NONE" })
set(0, "Comment", { fg = "#5a5a5a", italic = true })
set(0, "Constant", { fg = "#c490d0" })
set(0, "String", { fg = "#00b300" })
set(0, "Character", { link = "String" })
set(0, "Number", { fg = "#c490d0" })
set(0, "Boolean", { fg = "#c490d0" })
set(0, "Float", { fg = "#c490d0" })
set(0, "Identifier", { fg = "#dadada" })
set(0, "Function", { fg = "#88ddcc" })
set(0, "Statement", { fg = "#ffcc00" })
set(0, "Conditional", { fg = "#ffcc00" })
set(0, "Repeat", { link = "Statement" })
set(0, "Keyword", { fg = "#ffcc00" })
set(0, "Operator", { fg = "#dadada" })
set(0, "PreProc", { fg = "#00b300" })
set(0, "Include", { fg = "#00b300" })
set(0, "Define", { fg = "#00b300" })
set(0, "Macro", { fg = "#00b300" })
set(0, "Type", { fg = "#e8a060" })
set(0, "Typedef", { fg = "#e8a060" })
set(0, "Special", { link = "PreProc" })

-- UI
set(0, "CursorLineNr", { fg = "#dadada", bg = "#282828" })
set(0, "LineNr", { fg = "#dadada" })
set(0, "SignColumn", { fg = "#00b300", bg = "#000000" })
set(0, "Search", { fg = "#000000", bg = "#ffcc00" })
set(0, "Visual", { bg = "#3a3a3a" })
set(0, "StatusLine", { fg = "#dadada", bg = "#000000" })
set(0, "StatusLineNC", { fg = "#dadada", bg = "#000000" })

-- Popup menu / completion
set(0, "Pmenu", { fg = "#dadada", bg = "#181818" })
set(0, "PmenuSel", { fg = "#000000", bg = "#ffcc00" })
set(0, "PmenuSbar", { bg = "#181818" })
set(0, "PmenuThumb", { bg = "#3a3a3a" })

set(0, "DiagnosticError", { fg = "#ff6b6b" })
set(0, "DiagnosticWarn", { fg = "#ffcc00" })
set(0, "DiagnosticInfo", { fg = "#00b300" })
set(0, "DiagnosticHint", { fg = "#dadada" })

set(0, "DiagnosticVirtualTextError", { fg = "#dadada", bg = "NONE" })
set(0, "DiagnosticVirtualTextWarn", { fg = "#dadada", bg = "NONE" })
set(0, "DiagnosticVirtualTextInfo", { fg = "#dadada", bg = "NONE" })
set(0, "DiagnosticVirtualTextHint", { fg = "#dadada", bg = "NONE" })

set(0, "@comment", { fg = "#5a5a5a", italic = true })
set(0, "@string", { fg = "#00b300" })
set(0, "@keyword", { fg = "#ffcc00" })
set(0, "@keyword.operator", { fg = "#ffcc00" })
set(0, "@variable", { fg = "#dadada" })
set(0, "@function", { fg = "#88ddcc" })
set(0, "@type", { fg = "#e8a060" })
set(0, "@attribute", { fg = "#dadada" })
set(0, "@constant", { fg = "#c490d0" })
set(0, "@constant.builtin", { fg = "#c490d0" })
set(0, "@number", { fg = "#c490d0" })
set(0, "@boolean", { fg = "#c490d0" })
set(0, "@property", { fg = "#dadada" })
set(0, "@parameter", { fg = "#dadada" })

set(0, "markdownH1", { link = "PreProc" })
set(0, "markdownH2", { link = "PreProc" })
set(0, "markdownH3", { link = "PreProc" })
set(0, "markdownH4", { link = "PreProc" })
set(0, "markdownH5", { link = "PreProc" })
set(0, "markdownH6", { link = "PreProc" })
set(0, "markdownHeadingDelimiter", { link = "PreProc" })

set(0, "NormalFloat", { bg = "#000000" })
set(0, "FloatBorder", { fg = "#dadada", bg = "#000000" })
set(0, "ColorColumn", { bg = "#1a1a1a" })
set(0, "CursorLine", { bg = "#121212" })

-- UI and plugin highlights belong to the colorscheme so reloads stay consistent.
set(0, "NormalNC", { link = "Normal" })
set(0, "EndOfBuffer", { bg = "NONE" })
set(0, "@function.builtin", { fg = "#88ddcc" })
set(0, "@function.method", { fg = "#88ddcc" })
set(0, "@type.builtin", { fg = "#e8a060" })
set(0, "@number.float", { fg = "#c490d0" })
set(0, "@tag", { fg = "#ff6b6b" })
set(0, "@tag.delimiter", { fg = "#ff6b6b" })
set(0, "@keyword.return", { fg = "#ff6b6b" })
set(0, "@keyword.exception", { fg = "#ff6b6b" })
set(0, "MatchParen", { fg = "#c490d0", bold = true, underline = true })
set(0, "IncSearch", { fg = "#000000", bg = "#88ddcc" })
set(0, "CurSearch", { fg = "#000000", bg = "#c490d0" })
set(0, "DiffAdd", { fg = "#a5d6a7", bg = "#0a2010" })
set(0, "DiffChange", { fg = "#e8a060", bg = "#201a0a" })
set(0, "DiffDelete", { fg = "#ff6b6b", bg = "#200a0a" })
set(0, "DiffText", { fg = "#ffcc00", bg = "#3a2000", bold = true })
set(0, "WinBar", { fg = "#dadada", bold = true })
set(0, "WinBarNC", { fg = "#888888" })
set(0, "ConflictMarker", { link = "DiagnosticError" })
set(0, "YankHighlight", { link = "Search" })
set(0, "OilCreate", { link = "DiagnosticOk" })
set(0, "OilDelete", { link = "DiagnosticError" })
set(0, "OilMove", { link = "DiagnosticWarn" })
set(0, "OilCopy", { link = "DiagnosticInfo" })
set(0, "BlinkCmpLabelMatch", { link = "Search" })
set(0, "BlinkCmpMenuSelection", { link = "PmenuSel" })
set(0, "FzfLuaTitle", { link = "Title" })
set(0, "FzfLuaPreviewTitle", { link = "Title" })
set(0, "FzfLuaHeaderBind", { link = "Special" })

-- Complete the standard syntax families without introducing new colors.
set(0, "Label", { link = "Statement" })
set(0, "Exception", { link = "DiagnosticError" })
set(0, "StorageClass", { link = "Type" })
set(0, "Structure", { link = "Type" })
set(0, "PreCondit", { link = "PreProc" })
set(0, "SpecialChar", { link = "Special" })
set(0, "SpecialComment", { link = "Comment" })
set(0, "Delimiter", { link = "Identifier" })
set(0, "Error", { link = "DiagnosticError" })
set(0, "Todo", { fg = "#ffcc00", bold = true })
set(0, "Title", { fg = "#88ddcc", bold = true })
set(0, "Directory", { link = "Function" })
set(0, "DiagnosticOk", { fg = "#00b300" })

-- Keep parser captures consistent with traditional syntax highlighting.
set(0, "@keyword.repeat", { link = "Repeat" })
set(0, "@keyword.conditional", { link = "Conditional" })
set(0, "@keyword.import", { link = "Include" })
set(0, "@keyword.directive", { link = "PreProc" })
set(0, "@character", { link = "Character" })
set(0, "@string.escape", { link = "SpecialChar" })
set(0, "@operator", { link = "Operator" })
set(0, "@punctuation", { link = "Delimiter" })
set(0, "@variable.parameter", { link = "Identifier" })
set(0, "@variable.member", { link = "Identifier" })
set(0, "@label", { link = "Label" })

set(0, "markdownLinkText", { fg = "#88ddcc", underline = true })
set(0, "markdownUrl", { link = "Comment" })
set(0, "markdownCode", { link = "Type" })
set(0, "markdownCodeBlock", { link = "Type" })
